export const CHANGE_INITIALIZED_APP_REQUESTED = 'CHANGE_INITIALIZED_APP_REQUESTED';
export const CHANGE_INITIALIZED_APP_SUCCEED = 'CHANGE_INITIALIZED_APP_SUCCEED';

export const CHANGE_SIDEBAR_APP_REQUESTED = 'CHANGE_SIDEBAR_APP_REQUESTED';
export const CHANGE_SIDEBAR_APP_SUCCEED = 'CHANGE_SIDEBAR_APP_SUCCEED';
