export const APP_INITIALIZED_REQUESTED = 'APP_INITIALIZED_REQUESTED';
export const APP_INITIALIZED_SUCCEED = 'APP_INITIALIZED_SUCCEED';

export const APP_SIDEBAR_REQUESTED = 'APP_SIDEBAR_REQUESTED';
export const APP_SIDEBAR_SUCCEED = 'APP_SIDEBAR_SUCCEED';
